# Generated by Django 4.2 on 2023-05-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmeh', '0002_ordinacija_centrala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='ordinacijarez',
            field=models.ForeignKey(db_column='OrdinacijaRez', null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmeh.ordinacija'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='pacijent',
            field=models.ForeignKey(db_column='Pacijent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmeh.pacijent'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='stomatolog',
            field=models.ForeignKey(db_column='Stomatolog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmeh.stomatolog'),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='usluga',
            field=models.ForeignKey(db_column='Usluga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmeh.usluga'),
        ),
        migrations.AlterField(
            model_name='stomatolog',
            name='ordinacija',
            field=models.ForeignKey(db_column='Ordinacija', null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmeh.ordinacija'),
        ),
    ]
