# Generated by Django 4.2 on 2023-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmeh', '0003_alter_rezervacija_ordinacijarez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stomatolog',
            name='biografija',
            field=models.CharField(db_column='Biografija', max_length=1000),
        ),
    ]
