# Generated by Django 4.2 on 2023-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmeh', '0004_alter_stomatolog_biografija'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='ordinacija_ime',
            field=models.CharField(db_column='OrdinacijaIme', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='pacijent_ime',
            field=models.CharField(db_column='PacijentIme', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='stomatolog_ime',
            field=models.CharField(db_column='StomatologIme', default='', max_length=50),
        ),
    ]
